Repository openfun/potsie, pull requests merged in 2021-06, with the labels that each got.

#1 ✨(project) add core workspace
  .gitignore
  Dockerfile
  Makefile
  README.md
  bin/jb
  bin/jsonnet
  bin/watch
  docker-compose.yml
  env.d/app
  env.d/grafana
  env.d/postgresql
  etc/grafana/provisioning/dashboards/potsie.yaml
  jsonnetfile.json
  jsonnetfile.lock.json
  src/dashboards/videos/details.jsonnet
Labels: feature, needs review

#4 ✨(project) add Jsonnet linter and formatter
  Dockerfile
  Makefile
  README.md
  bin/jsonnet-lint
  bin/jsonnetfmt
  src/dashboards/videos/details.jsonnet
Labels: improvement, needs review

#5 👷(project) add base CI
  .circleci/config.yml
  .gitlint
  .gitlint.d/gitlint_emoji.py
  CHANGELOG.md
Labels: feature, needs review

#7 👷(project) fix release title
  .circleci/config.yml
Labels: improvement, needs review

#9 🔖(minor) bump release to 0.1.0
  CHANGELOG.md
  VERSION
Labels: FUN, needs review

#11 ✨(dashboard) add complete video views panel
  CHANGELOG.md
  src/dashboards/videos/details.jsonnet
Labels: feature, needs review

#13 ✨(dashboard) add course video events distribution panel
  CHANGELOG.md
  src/dashboards/videos/details.jsonnet
Labels: feature

#12 ✨(dashboard) add video event distribution during the video
  CHANGELOG.md
  Makefile
  docker-compose.yml
  env.d/grafana
  src/dashboards/videos/details.jsonnet
Labels: feature
